sequenceDiagram
User ->> Afficheur: lancerJeu()
User ->> Afficheur: introduireJeu()
User ->> Afficheur: afficherRegles()
User ->> Afficheur: afficherCarteVie()
User ->> Afficheur: afficherCartePopularite()
User ->> Afficheur: afficherCarteCopie()
User ->> Afficheur: afficherMain()
User ->> Afficheur: voirMainAdversaire()
User ->> Afficheur: afficherJoueur()
User ->> Afficheur: selectionnerNom()
User ->> Afficheur: piocherCarte()
User ->> Afficheur: piocherMain()
User ->> Afficheur: selectionnerCarte()
User ->> Afficheur: debuterTour()
User ->> Afficheur: afficherGagnant()
User ->> Afficheur: jouerCarte()
User ->> Carte: getNom()
User ->> Carte: getDescription()
User ->> CarteAttaque: afficherCarte()
User ->> CarteAttaque: getType()
User ->> CarteAttaque: actionCarte()
User ->> CarteCopier: afficherCarte()
User ->> CarteCopier: getType()
User ->> CarteCopier: actionCarte()
User ->> CarteDiffamation: afficherCarte()
User ->> CarteDiffamation: getType()
User ->> CarteDiffamation: actionCarte()
User ->> CarteFinale: getType()
User ->> CartePopularite: afficherCarte()
User ->> CartePopularite: getType()
User ->> CartePopularite: actionCarte()
User ->> CarteSoin: afficherCarte()
User ->> CarteSoin: getType()
User ->> CarteSoin: actionCarte()
User ->> Jeu: lancerJeu()
User ->> Joueur: getNom()
User ->> Joueur: getVie()
User ->> Joueur: getPopularite()
User ->> Joueur: getCarte()
User ->> Joueur: modifPopularite()
User ->> Joueur: modifVie()
User ->> Joueur: piocherCarte()
User ->> Joueur: afficherCarte()
User ->> Joueur: afficherMain()
User ->> Joueur: piocherMain()
User ->> Joueur: jouerCarte()
User ->> Joueur: verifierVictoire()
User ->> Joueur: echangerCarte()
User ->> Pioche: melangerPioche()
User ->> Pioche: piocherCarte()
Afficheur ->> out: println()
Afficheur ->> out: println()
Afficheur ->> out: println()
Afficheur ->> chaine: append()
Afficheur ->> chaine: append()
Afficheur ->> out: println()
Afficheur ->> chaine: append()
Afficheur ->> chaine: append()
Afficheur ->> out: println()
Afficheur ->> chaine: append()
Afficheur ->> out: println()
Afficheur ->> out: println()
Afficheur ->> out: println()
Afficheur ->> chaine: append()
Afficheur ->> chaine: append()
Afficheur ->> out: println()
Afficheur ->> out: print()
Afficheur ->> scan: next()
Afficheur ->> out: println()
Afficheur ->> out: println()
Afficheur ->> out: println()
Afficheur ->> Integer: parseInt()
Afficheur ->> scan: next()
Afficheur ->> out: println()
Afficheur ->> out: println()
Afficheur ->> out: println()
Afficheur ->> out: println()
Afficheur ->> out: println()
Afficheur ->> out: println()
Afficheur ->> out: println()
Senario ->> Jeu: setAfficheur()
Senario ->> jeu: lancerJeu()
CarteAttaque ->> afficheur: afficherCarteVie()
CarteAttaque ->> adversaire: modifVie()
CarteCopier ->> afficheur: afficherCarteCopie()
CarteCopier ->> afficheur: voirMainAdversaire()
CarteCopier ->> adversaire: afficherMain()
CarteCopier ->> afficheur: selectionnerCarte()
CarteCopier ->> adversaire: getCarte()
CarteCopier ->> afficheur: jouerCarte()
CarteCopier ->> adversaire: getNom()
CarteCopier ->> joueur: echangerCarte()
CarteCopier ->> joueur: jouerCarte()
CarteDiffamation ->> afficheur: afficherCartePopularite()
CarteDiffamation ->> adversaire: modifPopularite()
CartePopularite ->> afficheur: afficherCartePopularite()
CartePopularite ->> joueur: modifPopularite()
CarteSoin ->> afficheur: afficherCarteVie()
CarteSoin ->> joueur: modifVie()
Jeu ->> afficheur: afficherGagnant()
Jeu ->> joueur: getNom()
Jeu ->> afficheur: lancerJeu()
Jeu ->> afficheur: introduireJeu()
Jeu ->> afficheur: afficherRegles()
Jeu ->> pioche: melangerPioche()
Jeu ->> afficheur: afficherJoueur()
Jeu ->> joueur: getNom()
Jeu ->> joueur: getVie()
Jeu ->> joueur: getPopularite()
Jeu ->> afficheur: afficherJoueur()
Jeu ->> adversaire: getNom()
Jeu ->> adversaire: getVie()
Jeu ->> adversaire: getPopularite()
Jeu ->> joueur: piocherMain()
Jeu ->> adversaire: piocherMain()
Jeu ->> afficheur: debuterTour()
Jeu ->> joueur: getNom()
Jeu ->> joueur: piocherCarte()
Jeu ->> afficheur: afficherMain()
Jeu ->> joueur: afficherMain()
Jeu ->> afficheur: selectionnerCarte()
Jeu ->> afficheur: jouerCarte()
Jeu ->> joueur: getNom()
Jeu ->> joueur: jouerCarte()
Jeu ->> afficheur: afficherJoueur()
Jeu ->> joueur: getNom()
Jeu ->> joueur: getVie()
Jeu ->> joueur: getPopularite()
Jeu ->> afficheur: afficherJoueur()
Jeu ->> adversaire: getNom()
Jeu ->> adversaire: getVie()
Jeu ->> adversaire: getPopularite()
Jeu ->> joueur: verifierVictoire()
Joueur ->> pioche: piocherCarte()
Joueur ->> afficheur: piocherCarte()
Joueur ->> pioche: piocherCarte()
Joueur ->> pioche: piocherCarte()
Joueur ->> pioche: piocherCarte()
Joueur ->> pioche: piocherCarte()
Joueur ->> afficheur: piocherMain()
Joueur ->> adversaire: getVie()
Pioche ->> SecureRandom: getInstanceStrong()
Pioche ->> e: printStackTrace()
Pioche ->> random: nextInt()