sequenceDiagram
User ->> Afficheur: lancerJeu()
User ->> Afficheur: introduireJeu()
User ->> Afficheur: afficherRegles()
User ->> Afficheur: afficherCarteVie()
User ->> Afficheur: afficherCartePopularite()
User ->> Afficheur: afficherCarteCopie()
User ->> Afficheur: afficherMain()
User ->> Afficheur: voirMainAdversaire()
User ->> Afficheur: afficherJoueur()
User ->> Afficheur: selectionnerNom()
User ->> Afficheur: piocherCarte()
User ->> Afficheur: piocherMain()
User ->> Afficheur: selectionnerCarte()
User ->> Afficheur: debuterTour()
User ->> Afficheur: afficherGagnant()
User ->> Afficheur: jouerCarte()
User ->> Carte: getNom()
User ->> Carte: getDescription()
User ->> CarteAttaque: afficherCarte()
User ->> CarteAttaque: getType()
User ->> CarteAttaque: actionCarte()
User ->> CarteCopier: afficherCarte()
User ->> CarteCopier: getType()
User ->> CarteCopier: actionCarte()
User ->> CarteDiffamation: afficherCarte()
User ->> CarteDiffamation: getType()
User ->> CarteDiffamation: actionCarte()
User ->> CarteFinale: getType()
User ->> CartePopularite: afficherCarte()
User ->> CartePopularite: getType()
User ->> CartePopularite: actionCarte()
User ->> CarteSoin: afficherCarte()
User ->> CarteSoin: getType()
User ->> CarteSoin: actionCarte()
User ->> Jeu: lancerJeu()
User ->> Joueur: getNom()
User ->> Joueur: getVie()
User ->> Joueur: getPopularite()
User ->> Joueur: getCarte()
User ->> Joueur: modifPopularite()
User ->> Joueur: modifVie()
User ->> Joueur: piocherCarte()
User ->> Joueur: afficherCarte()
User ->> Joueur: afficherMain()
User ->> Joueur: piocherMain()
User ->> Joueur: jouerCarte()
User ->> Joueur: verifierVictoire()
User ->> Joueur: echangerCarte()
User ->> Pioche: melangerPioche()
User ->> Pioche: piocherCarte()